del /Q out\*
mkdir out
copy avatar.png out\
copy reply.png out\
copy retweet.png out\
copy fav.png out\
emcc main.cpp --js-library library_js.js -lwebgl.js -s TEXTDECODER=2 -s MINIMAL_RUNTIME=1 -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s ENVIRONMENT=web -s MIN_FIREFOX_VERSION=70 -s MIN_SAFARI_VERSION=130000 -s MIN_IE_VERSION=0x7FFFFFFF -s MIN_EDGE_VERSION=79 -s MIN_CHROME_VERSION=80 -s ABORTING_MALLOC=0 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 -s GL_EXTENSIONS_IN_PREFIXED_FORMAT=0 -s GL_EMULATE_GLES_VERSION_STRING_FORMAT=0 -s GL_SUPPORT_SIMPLE_ENABLE_EXTENSIONS=0 -s SUPPORT_ERRNO=0 -s FILESYSTEM=0 -o out\main.html -g
